### ISSUE TITLE
Jeu de données d'actualité

### ISSUE THREAD

**Issue by Welsh44** [spyrales/organisation#11]
Pour aider les débutants, un jeu de données d'actualité vient d'être mis en ligne par Santé Publique France en open data : https://www.data.gouv.fr/fr/datasets/donnees-relatives-a-lepidemie-du-covid-19/

**Comment by strainel** [comment]
on pourrait faire un exercice dessus... nombre de patients h/f hospitalisés France entière, Dom, France métro, mais aussi de la dataviz. une carte, une carte dynamique, etc.

**Comment by RLesur** [comment]
@strainel exercice... ou bien un moment d'émulation un peu à la manière du [TidyTuesday](https://github.com/rfordatascience/tidytuesday) ?

**Comment by ViolainePoirot** [comment]
Bonjour, c'est une bonne idée de lancer les gens sur les données COVID. J'avais aussi cette source qui recense le nombre de cas confirmés par jour et par pays du monde : https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv

**Comment by RLesur** [comment]
@ViolainePoirot @Welsh44 si vous êtes intéressés pour lancer une action sur ce sujet, vous pouvez prendre les choses en main. Vous avez les droits de création de repo dans l'organisation spyrales

**Comment by strainel** [comment]
que pensez-vous d'organiser un événement "spyrales fait son show" chaque semaine, sur un jeu de données différent, en demandant aux **spyralien.es de partager leurs réalisations** ?  @RLesur proposait quelque chose comme http://tidytuesday.com 
On pourrait ainsi essayer de faire un petit tour des politiques de nos ministères ou de nos services ? 

- Semaine 1 (vendredi de la semaine prochaine) : COVID (actualité oblige)
- S2 : émission gaz à effet de serre (ou un autre jeu de données sur l'écologie)
- S3 : statistique sur les décisions de justice
- S4 : données demande de valeur foncière (DVF)
- S5 : démographie des entreprises
- S6 : statistiques sur les bureaux de vote 
- S7 : ...

Le jeu de données doit rester globalement accessible à tous, donc à peu près documenté et en opendata.

**Comment by strainel** [comment]
j'ai créé un repo "la piscine" pour créer un événement chaque semaine avec un jeu de données.
spyrales/la-piscine#1

qu'en pensez-vous ?

**Comment by RLesur** [comment]
Effectivement, je pense qu'un repo dédié est nécessaire pour cette action.
