### ISSUE TITLE
invitation pour agent externe

### ISSUE THREAD

**Issue by gmat** [spyrales/organisation#16]
Bonjour,
mon domaine mail pro n'est pas référencé pour m'inscrire sur https://www.tchap.gouv.fr/, comment vous soumettre une demande d'invitation ?
J'ai appris votre initiative par une liste diffusion avec comme consigne de demander une invitation sur tchap auprès de Stéphane TRAINEL ou Romain LESUR... Au moins j'ai trouvé @RLesur sur ce dépôt.
Merci,

**Comment by strainel** [comment]
bonsoir,
le plus simple est de nous laisser un message via le formulaire de contact sur le site https://spyrales.netlify.com ; on pourra utiliser votre email pour vous inviter.

**Comment by gmat** [comment]
ok super simple je fais ça alors.
Merci bon we
je ferme le ticket
