### ISSUE TITLE
Termes employés

### ISSUE THREAD

**Issue by RLesur** [spyrales/organisation#7]
En relisant le terme "data-codeurs", j'ai réalisé que cette expression serait susceptible de faire peur à pas mal de monde chez moi (j'ai des B et C qui sont intéressés pour apprendre, découvrir... mais qui ne se reconnaîtront jamais dans une telle expression).
Je me demande si on devrait pas faire attention à employer des termes les plus inclusifs possible.

Qu'en pensez-vous ?

**Comment by strainel** [comment]
je clos également...
